# Generated by Django 3.1 on 2020-08-27 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200819_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
