# Generated by Django 2.1.1 on 2020-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200819_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='status',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='fa_status',
            field=models.CharField(blank=True, choices=[('fa', 'Favorite'), ('un_fa', 'Unfavorite')], default='un_fa', help_text='Book has not been mark favorite', max_length=5),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='mark_status',
            field=models.CharField(blank=True, choices=[('nr', 'Not read'), ('r_ed', 'Readed'), ('r_ing', 'Reading')], default='n', help_text='Book has not been read', max_length=5),
        ),
    ]
