# Generated by Django 3.0.8 on 2020-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200819_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(blank=True, choices=[(1, 'Awful'), (2, 'Fair'), (3, 'Good'), (4, 'Great'), (5, 'Excellent')]),
        ),
    ]
