# Generated by Django 3.1 on 2020-08-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200825_2200'),
        ('review', '0003_follow_date_added'),
    ]

    operations = [
    ]
