# Generated by Django 2.1.1 on 2020-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200825_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='mark_status',
            field=models.CharField(blank=True, choices=[('nr', 'Not read'), ('r_ed', 'Readed'), ('r_ing', 'Reading')], default='nr', help_text='Book has not been read', max_length=5),
        ),
    ]
