# Generated by Django 3.1 on 2020-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_merge_20200827_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Fair'), (3, 'Good'), (4, 'Great'), (5, 'Excellent')], default=5),
        ),
    ]
