# Generated by Django 2.1.1 on 2020-08-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20200825_2200'),
        ('review', '0005_auto_20200827_0827'),
    ]

    operations = [
    ]
