# Generated by Django 2.1.1 on 2020-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_merge_20200827_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Fair'), (3, 'Good'), (4, 'Great'), (5, 'Excellent')], default=5),
        ),
    ]
