# Generated by Django 3.1 on 2020-08-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20200827_1539'),
        ('review', '0005_auto_20200827_1729'),
    ]

    operations = [
    ]
