# Generated by Django 2.1.1 on 2020-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20200828_0811'),
        ('review', '0005_auto_20200827_1729'),
    ]

    operations = [
    ]
