# Generated by Django 3.1 on 2020-08-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_merge_20200828_0909'),
        ('review', '0009_merge_20200828_1559'),
    ]

    operations = [
    ]
