# Generated by Django 3.0.8 on 2020-08-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_merge_20200828_0836'),
        ('review', '0009_merge_20200828_1559'),
    ]

    operations = [
    ]
