# Generated by Django 3.1 on 2020-08-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_merge_20200831_0536'),
        ('review', '0008_merge_20200828_0836'),
    ]

    operations = [
    ]
