# Generated by Django 3.0.8 on 2020-08-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_merge_20200831_0612'),
        ('review', '0010_merge_20200831_0933'),
    ]

    operations = [
    ]
