# Generated by Django 2.1.1 on 2020-08-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_merge_20200831_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('fo', 'Follow'), ('fa', 'Favorite'), ('un_fo', 'Unfollow'), ('un_fa', 'Unfavorite'), ('ma_ed', 'Mark read'), ('ma_ing', 'Mark reading'), ('rv', 'Review')], max_length=200),
        ),
    ]
