# Generated by Django 3.1.1 on 2020-09-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20200831_1816'),
        ('review', '0012_merge_20200831_1139'),
    ]

    operations = [
    ]
