# Generated by Django 2.1.1 on 2020-09-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20200831_1816'),
        ('review', '0012_merge_20200831_1139'),
    ]

    operations = [
    ]
