# Generated by Django 3.1.1 on 2020-09-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20200904_0343'),
        ('review', '0013_merge_20200903_1106'),
    ]

    operations = [
    ]
