# Generated by Django 2.1.1 on 2020-09-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200831_1816'),
        ('notifications', '0002_auto_20200831_1143'),
    ]

    operations = [
    ]
