# Generated by Django 3.1.1 on 2020-09-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200831_1816'),
        ('notifications', '0002_auto_20200831_1143'),
    ]

    operations = [
    ]
