# Generated by Django 3.1.1 on 2020-09-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_20200903_1106'),
        ('notifications', '0003_merge_20200904_0203'),
    ]

    operations = [
    ]
